<ips:template parameters="$category" />

{{if $category->collabs_enable and $category->can( 'view' )}}
<div class="ipsDataItem_stats ipsDataItem_statsLarge">
	<dl>
		<dt class="ipsDataItem_stats_number">{$category->getContentItemCount()}</dt>
		<dd class="ipsDataItem_stats_type ipsType_light">{$category->collab_plural}</dd>
	</dl>
</div>
<ul class='ipsDataItem_lastPoster ipsDataItem_withPhoto'>
{{foreach \IPS\collab\Collab::getItemsWithPermission( array( array( 'category_id=?', $category->_id ) ), 'last_post DESC', 1 ) as $collab}}
		<li>{template="userPhoto" app="core" group="global" params="$collab->author(), 'tiny'"}	</li>
		<li><a href="{$collab->url()}" class='ipsType_break ipsContained' title="{$collab->mapped( 'title' )}">{truncate="$collab->mapped( 'title' )" length="30"}</a></li>	
		{{if $latestContentItems = $collab->getLatestContent( 1 )}}
			{{$latestContent = array_shift( $latestContentItems );}}
			<li>{lang="byline_nodate" htmlsprintf="$latestContent->author()->link()"}</li>
			<li class="ipsType_light">{datetime="$latestContent->mapped( 'date' )"}</li>
		{{else}}
			<li>{lang="byline_nodate" htmlsprintf="$collab->author()->link()"}</li>
			<li class="ipsType_light">{datetime="$collab->last_post"}</li>
		{{endif}}
{{endforeach}}
</ul>
{{endif}}