<ips:template parameters="$table, $headers, $rows" />
{{$rowIds = array();}}
{{foreach $rows as $row}}
	{{$idField = $row::$databaseColumnId;}}
	{{$rowIds[] = $row->$idField;}}
{{endforeach}}
{{$iposted = ( method_exists( $table, 'container' ) AND $table->container() !== NULL ) ? $table->container()->contentPostedIn( null, $rowIds ) : array();}}
{{if count( $rows )}}
	{{$rowCount=0;}}
	{{foreach $rows as $row}}
		{{$rowCount++;}}
		{{$idField = $row::$databaseColumnId;}}
		<li class="ipsDataItem ipsDataItem_responsivePhoto {{if $row->unread()}}ipsDataItem_unread{{else}}ipsDataItem_read{{endif}} {{if method_exists( $row, 'tableClass' ) && $row->tableClass()}}ipsDataItem_{$row->tableClass()}{{endif}} {{if $row->hidden()}}ipsModerated{{endif}}" data-rowID='{$row->$idField}'>
			<div class='ipsDataItem_icon ipsPos_top'>
				{{$member_count = $row->memberships( array ( 'statuses' => \IPS\collab\COLLAB_MEMBER_ACTIVE, 'count' => true ) );}}
				<span style="opacity:1" class='ipsItemStatus ipsItemStatus_large collabStatusIcon {{if ! $row->unread()}}ipsItemStatus_read{{endif}} '>
					{{if $row->isFull()}}
						<i class="fa fa-circle"></i>
					{{else}}
					  	<i class="fa fa-circle-o"></i>
					{{endif}}
					<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_style3 membershipCount" data-ipstooltip title='{lang="collab_active_members_count" pluralize="$member_count"}'>
						{$member_count}
					</span>
					{{if $membership = $row->getMembership()}}
						{{if $membership->status === \IPS\collab\COLLAB_MEMBER_ACTIVE}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive membershipStatus" data-ipsTooltip title='{lang="collab_youre_active" sprintf="$collab->collab_singular"}'><i class='fa fa-user'></i></span>
						{{endif}}
						{{if $membership->status === \IPS\collab\COLLAB_MEMBER_PENDING}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_intermediary membershipStatus" data-ipsTooltip title='{lang="collab_youre_pending" sprintf="$collab->collab_singular"}'><i class='fa fa-user'></i></span>
						{{endif}}
						{{if $membership->status === \IPS\collab\COLLAB_MEMBER_INVITED}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_intermediary membershipStatus" data-ipsTooltip title='{lang="collab_youre_invited" sprintf="$collab->collab_singular"}'><i class='fa fa-bullhorn'></i></span>
						{{endif}}
						{{if $membership->status === \IPS\collab\COLLAB_MEMBER_BANNED}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_negative membershipStatus" data-ipsTooltip title='{lang="collab_youre_banned" sprintf="$collab->collab_singular"}'><i class='fa fa-times-circle'></i></span>
						{{endif}}
					{{endif}}
				</span>
			</div>
			<div class='ipsDataItem_main'>
				<h4 class='ipsDataItem_title marg0 ipsType_break'>
					{{if $row->locked()}}
						<i class='fa fa-lock' data-ipsTooltip title='{lang="topic_locked"}'></i>
					{{endif}}
										
					{{if $row->prefix()}}
						{template="prefix" group="global" app="core" params="$row->prefix( TRUE ), $row->prefix()"}
					{{endif}}
					
					<a href='{$row->url()}' {{if $row->tableHoverUrl and $row->canView()}}data-ipsHover data-ipsHover-target='{$row->url()->setQueryString('preview', 1)}' data-ipsHover-timeout='1.5'{{endif}}>
						{{if $row->mapped('title')}}{lang="$row->mapped('title')" wordbreak="true"}{{else}}<em class="ipsType_light">{lang="content_deleted"}</em>{{endif}}
					</a>
				</h4>
				<span>
					{{if $row->hidden() === -1}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$row->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
					{{elseif $row->hidden() === 1}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
					{{endif}}							
					{{if $row->mapped('pinned')}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
					{{endif}}
					{{if $row->mapped('featured')}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
					{{endif}}
					{{if $row->is_template and ( $row->canMakeModel() or $row->canUnmakeModel() )}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_intermediary" data-ipsTooltip title='{lang="collab_marked_model"}'><i class='fa fa-flag'></i></span>
					{{endif}}
					{{if count( $row->tags() )}}
						&nbsp;&nbsp;
						{template="tags" group="global" app="core" params="$row->tags(), true, true"}
					{{endif}}
				</span>
				{{$collabData = $row->collab_data;}}
				{{if $row->enabledNodes() and $collabData[ '_items' ][ 'grand_total' ]}}
					<ul class="ipsDataItem_subList ipsList_inline" style="margin-top:3px">
						{{foreach $row->enabledNodes() as $app => $configured}}
							{{foreach $configured[ 'nodes' ] as $node}}
								{{if $total_items = $collabData[ '_items' ][ 'node_totals' ][ $node[ 'nid' ] ]}}
									<li class="">
										{$node[ 'content_name' ]} ({$total_items})
									</li>
								{{endif}}
							{{endforeach}}
						{{endforeach}}
					</ul>
				{{endif}}
				<div class='ipsDataItem_meta ipsType_reset ipsType_light ipsType_blendLinks'>
					{truncate="$row->short_description" length="256"}
				</div>
			</div>
			{{foreach $row->stats(TRUE) as $k => $v}}
				{{if $k == 'items'}}
					<div class="ipsDataItem_stats ipsDataItem_statsLarge">
						<dl>
							<dt class="ipsDataItem_stats_number">{$v}</dt>
							<dd class="ipsDataItem_stats_type ipsType_light">{lang="collab_contributions" pluralize="$v"}</dd>
						</dl>
					</div>
				{{endif}}
			{{endforeach}}
			<ul class='ipsDataItem_lastPoster ipsDataItem_withPhoto'>
				{{if $latestContentItems = $row->getLatestContent( 1 )}}
					{{$latestContent = array_shift( $latestContentItems );}}
					<li>{template="userPhoto" app="core" group="global" params="$latestContent->author(), 'tiny'"}</li>
					<li><a href="{$latestContent->url()->setQueryString( 'do', 'getNewComment' )}" class='ipsType_break ipsContained' title="{$latestContent->mapped( 'title' )}">{truncate="$latestContent->mapped( 'title' )" length="30"}</a></li>
					<li>{lang="byline_nodate" htmlsprintf="$latestContent->author()->link()"}</li>
					<li class="ipsType_light"><a href='{$latestContent->url()->setQueryString( 'do', 'getLastComment' )}' title='{lang="get_last_post"}' class='ipsType_blendLinks'>{datetime="$latestContent->mapped( 'date' )"}</a></li>
				{{else}}
					<li>
						{template="userPhoto" app="core" group="global" params="$row->author(), 'tiny'"}
					</li>
					<li>
						{$row->author()->link()|raw}
					</li>
					<li class="ipsType_light ipsResponsive_hidePhone">
						{{if $membership = $row->getMembership( $row->author() )}}
							{$membership->title()}
						{{else}}
							{$row->guestTitle()}
						{{endif}}
					</li>
				{{endif}}
			</ul>
			{{if $table->canModerate()}}
				<div class='ipsDataItem_modCheck'>
					<input type='checkbox' data-role='moderation' name="moderate[{$row->$idField}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{{if $row->tableStates()}}{$row->tableStates()}{{endif}}'>
				</div>
			{{endif}}
		</li>
	{{endforeach}}
{{endif}}