<ips:template parameters="$collab" />
<li>
	<a class='ipsButton ipsButton_important ipsButton_verySmall' data-ipsMenu data-ipsMenu-appendTo='#elEventHeader' id='elCollabMenu' href='#elCollabMenu_menu'>
		<i class='fa fa-bars'></i>&nbsp;<span class='ipsResponsive_hidePhone ipsResponsive_inline'>&nbsp;&nbsp;{lang="collab_menu" sprintf="$collab->collab_singular"} <i class='fa fa-caret-down'></i></span>
	</a>
	<ul class='ipsMenu ipsMenu_auto ipsHide' id='elCollabMenu_menu'>
		<li class='ipsMenu_item'>
			<a href='{$collab->url()}'>
				<i class='fa fa-home'></i>&nbsp;<span class='ipsResponsive_inline'>&nbsp;&nbsp;{lang="collab_homepage" sprintf="$collab->collab_singular"}</span>
			</a>
		</li>
	</ul>
</li>
