<ips:template parameters="$collab" />
{{if $collab->collabMenuItems()}}
<li>
	<a class='ipsButton ipsButton_important ipsButton_verySmall' id='elCollabMenu' href='#elCollabMenu_menu' data-ipsMenu>
		<i class='fa fa-bars'></i>&nbsp;<span class='ipsResponsive_hidePhone ipsResponsive_inline'>&nbsp;&nbsp;{lang="collab_menu" sprintf="$collab->collab_singular"} <i class='fa fa-caret-down'></i></span>
	</a>
	{template="menuItems" group="components" app="collab" params="$collab, $collab->collabMenuItems()"}
</li>
{{endif}}
