<ips:template parameters="$node" />

{{$content_read_class = "";}}
{{$nodeClass = get_class( $node );}}
{{$contentClass = $nodeClass::$contentItemClass;}}
{{if !$contentClass::containerUnread( $node ) && !$node->redirect_on}}
  {{$content_read_class = "ipsItemStatus_read";}}
{{endif}}

{{if $node->can('view')}}
	<li class="ipsDataItem ipsDataItem_responsivePhoto ipsClearfix" data-forumID="{$node->_id}">
		<div class="ipsDataItem_icon ipsDataItem_category">
			{{if $node->icon}}
				<img src="{$node->icon}" class='ipsItemStatus ipsItemStatus_custom {$content_read_class}'>
			{{elseif method_exists( $node, 'tableIcon' )}}
				<div class='ipsDataItem_icon ipsType_center ipsType_noBreak {$content_read_class}'>
					{$node->tableIcon()|raw}
				</div>
			{{else}}
				<span class='ipsItemStatus ipsItemStatus_large cForumIcon_normal {$content_read_class}'>
					<i class="fa fa-comments"></i>
				</span>
			{{endif}}
		</div>
		<div class="ipsDataItem_main">
			<h4 class="ipsDataItem_title ipsType_large">
				<a href="{$node->url()}">{$node->_title}</a>
				{{if $node->_locked}}
					<i class="fa fa-lock"></i>
				{{endif}}
			</h4>
			{{if $node->hasChildren()}}
				<ul class="ipsDataItem_subList ipsList_inline">
					{{foreach $node->children() as $subnode}}
						<li class="">
							<a href="{$subnode->url()}">{$subnode->_title}</a>
						</li>
					{{endforeach}}
				</ul>
			{{endif}}
			{{if $node->_description}}
				<div class='ipsDataItem_meta ipsType_light' data-ipsTruncate data-ipsTruncate-size='2 lines' data-ipsTruncate-type='remove'>
					{$node->_description}
				</div>
			{{elseif $node->description}}
				<div class="ipsDataItem_meta ipsType_richText">{$node->description|raw}</div>
			{{elseif $node->metaDescription()}}
				<div class='ipsDataItem_meta ipsType_light' data-ipsTruncate data-ipsTruncate-size='2 lines' data-ipsTruncate-type='remove'>
					{$node->metaDescription()|raw}
				</div>
			{{endif}}
		</div>
		{{if !$node->redirect_on}}
		<div class="ipsDataItem_stats ipsDataItem_statsLarge">
			{{if $contentClass and method_exists( $contentClass, 'contentCount' ) and $count = $contentClass::contentCount( $node, TRUE )}}
				<dl>
					<dt class="ipsDataItem_stats_number">{number="$count"}</dt>
					<dd class="ipsDataItem_stats_type ipsType_light">{lang="posts_no_number" pluralize="$count"}</dd>
				</dl>
			{{else}}
				{{if $node->_items}}
				<dl>
					<dd class='ipsDataItem_stats_type ipsType_light'>{lang="node_content_items" pluralize="$node->_items"}</dd>
				</dl>
				{{endif}}
				{{if $node->_comments}}
				<dl>
					<dd class='ipsDataItem_stats_type ipsType_light'>{lang="node_content_comments" pluralize="$node->_comments"}</dd>
				</dl>
				{{endif}}
				{{if $node->_reviews}}
				<dl>
					<dd class='ipsDataItem_stats_type ipsType_light'>{lang="node_content_reviews" pluralize="$node->_reviews"}</dd>
				</dl>
				{{endif}}
			{{endif}}
			{{if get_class( $node ) == 'IPS\forums\Forum' and \IPS\forums\Topic::modPermission( 'unhide', NULL, $node ) AND ( $node->queued_topics OR $node->queued_posts )}}
				<strong class='ipsType_warning ipsType_medium'>
					<i class='fa fa-warning'></i>
					{{if $node->queued_topics}}
						<a href='{$node->url()->setQueryString( array( 'advanced_search_submitted' => 1, 'topic_type' => 'queued_topics' ) )->csrf()}' data-ipsTooltip title='{lang="queued_topics_badge" pluralize="$node->queued_topics"}' class='ipsType_blendLinks'>{$node->queued_topics}</a>
					{{else}}
						<span class='ipsType_light'>0</span>
					{{endif}}
					/
					{{if $node->queued_posts}}
						<a href='{$node->url()->setQueryString( array( 'advanced_search_submitted' => 1, 'topic_type' => 'queued_posts' ) )->csrf()}' data-ipsTooltip title='{lang="queued_posts_badge" pluralize="$node->queued_posts"}' class='ipsType_blendLinks'>{$node->queued_posts}</a>
					{{else}}
						<span class='ipsType_light'>0</span>
					{{endif}}
				</strong>					
			{{endif}}
		</div>
		{{if get_class( $node ) == 'IPS\forums\Forum'}}
		<ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto">
			{{if $lastPost = $node->lastPost()}}
				<li>{template="userPhoto" app="core" group="global" params="$lastPost['author'], 'tiny'"}</li>
				<li><a href="{$lastPost['topic_url']->setQueryString( 'do', 'getNewComment' )}" class='ipsType_break ipsContained' title='{$lastPost['topic_title']}'>{truncate="$lastPost['topic_title']" length="30"}</a></li>
				<li>{lang="byline_nodate" htmlsprintf="$lastPost['author']->link()"}</li>
				<li class="ipsType_light"><a href='{$lastPost['topic_url']->setQueryString( 'do', 'getLastComment' )}' title='{lang="get_last_post"}' class='ipsType_blendLinks'>{datetime="$lastPost['date']"}</a></li>
			{{else}}
				<li class='ipsType_light ipsResponsive_showDesktop'>{{if $node->password}}{lang="no_forum_posts_password"}{{else}}{lang="no_forum_posts"}{{endif}}</li>
			{{endif}}
		</ul>
		{{elseif method_exists( $node, 'getLatestContentItem' )}}
		<ul class="ipsDataItem_lastPoster ipsDataItem_withPhoto">
			{{if $lastPost = $node->getLatestContentItem()}}
				<li>{template="userPhoto" app="core" group="global" params="\IPS\Member::load( $lastPost->mapped('author') ), 'tiny'"}</li>
				<li><a href="{$lastPost->url()}" class='ipsType_break ipsContained' title='{$lastPost->mapped('title')}'>{truncate="$lastPost->mapped('title')" length="30"}</a></li>
				<li>{lang="byline_nodate" htmlsprintf="\IPS\Member::load( $lastPost->mapped('author') )->link()"}</li>
				<li class="ipsType_light"><a href='{$lastPost->url()}' title='{lang="get_last_post"}' class='ipsType_blendLinks'>{datetime="$lastPost->mapped('date')"}</a></li>
			{{else}}
				<li class='ipsType_light ipsResponsive_showDesktop'>{lang="collab_no_content"}</li>
			{{endif}}
		</ul>		
		{{endif}}
		{{endif}}
	</li>
{{endif}}