<ips:template parameters="$node" />

{{$contentClass = $node::$contentItemClass;}}
{{$unread = $contentClass::containerUnread( $node );}}

{{if $node->can('view')}}
	<div data-role='patchworkItem' class="ipsAreaBackground_reset cForumGrid ipsClearfix" data-nodeID="{$node->_id}">

		<div class='ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix ipsPad ipsAreaBackground_light cForumGrid_forumInfo'>
			<span class='ipsPos_left'>
					{{if $node->icon}}
						<img src="{file="$node->icon" extension="forums_Icons"}" class='ipsImage cForumGrid_icon'>
					{{else}}
						<span class='ipsItemStatus ipsItemStatus_large cForumIcon_normal {{if !$unread}}ipsItemStatus_read{{endif}}'>
							<i class="fa fa-comments"></i>
						</span>
					{{endif}}
			</span>
			<div class='{{if $unread}}ipsDataItem_unread{{endif}}'>
				<h3  class='ipsDataItem_title ipsType_reset ipsType_large'>
					{{if $node->password && !$node->loggedInMemberHasPasswordAccess()}}
						<ahref="{$node->url()->setQueryString( 'passForm', '1' )}" data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="forum_requires_password"}'>{$node->_title}</a>
					{{else}}
						<a href="{$node->url()}">{$node->_title}</a>
					{{endif}}
				</h3>
				{{if !$node->redirect_on and isset( $node::$contentItemClass ) and $contentClass = $node::$contentItemClass}}
					{{$count = $contentClass::contentCount( $node, TRUE );}}
					<p class='ipsType_reset'>{lang="posts_number" pluralize="$count"}</p>
				{{endif}}
			</div>
		</div>
		
		{{if $node->hasChildren()}}
		<div class="ipsPad">
			<ul class="ipsList_inline">
				<li><strong>{lang="collab_cat_sub"}</strong></li>
				{{foreach $node->children() as $subnode}}
					<li class="{{if $contentClass::containerUnread( $subnode )}}ipsDataItem_unread{{endif}}">
						<span class="ipsDataItem_title" style="margin:0">
							<a href="{$subnode->url()}">{$subnode->_title}</a>
						</span>
					</li>
				{{endforeach}}
			</ul>
		</div>
		{{endif}}

		{{if $node->description}}
		<div class="ipsPad">
			<div class='ipsType_richText ipsType_medium'>{$node->description|raw}</div>
		</div>
		{{endif}}
		

		{{if !$node->redirect_on}}
			{{if method_exists( $node, 'lastPost' ) and $lastPost = $node->lastPost()}}
				<div class='ipsPhotoPanel ipsPhotoPanel_tiny ipsPad'>
					<hr class='ipsHr'>
					{template="userPhoto" app="core" group="global" params="$lastPost['author'], 'tiny'"}
					<div>
						<ul class='ipsList_reset'>
							<li><a href="{$lastPost['topic_url']}" class='ipsType_break' title='{$lastPost['topic_title']}'>{truncate="$lastPost['topic_title']" length="30"}</a></li>
							<li>{lang="byline_nodate" htmlsprintf="$lastPost['author']->link()"}, <span class='ipsType_light'>{datetime="$lastPost['date']"}<span></li>
						</ul>
					</div>
				</div>
			{{else}}
				<p class='ipsPad ipsType_light ipsType_reset'>{{if $node->password}}{lang="no_forum_posts_password"}{{else}}{lang="no_forum_posts"}{{endif}}</p>
			{{endif}}
		{{endif}}
		
	</div>
{{endif}}