<ips:template parameters="$node" />
{{if $node->can('view')}}
	<div data-role='patchworkItem' class="ipsAreaBackground_reset ipsPad cForumGrid ipsClearfix" data-nodeID="{$node->_id}">

		<div class='ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix'>
			<span class='ipsPos_left'>
					{{if $node->icon}}
						<img src="{file="$node->icon" extension="forums_Icons"}" class='ipsImage cForumGrid_icon'>
					{{else}}
						<span class='ipsItemStatus ipsItemStatus_large cForumIcon_normal'>
							<i class="fa fa-comments"></i>
						</span>
					{{endif}}
			</span>
			<div>
				<h3 class='ipsType_reset ipsType_large'>
					{{if $node->password && !$node->loggedInMemberHasPasswordAccess()}}
						<a href="{$node->url()->setQueryString( 'passForm', '1' )}" data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="forum_requires_password"}'>{$node->_title}</a>
					{{else}}
						<a href="{$node->url()}">{$node->_title}</a>
					{{endif}}
				</h3>
			</div>
		</div>
		
		{{if $node->hasChildren()}}
			<br>
			<ul class="ipsList_inline">
				<li><strong>{lang="collab_cat_sub"}</strong></li>
				{{foreach $node->children() as $subnode}}
					<li class="">
						<a href="{$subnode->url()}">{$subnode->_title}</a>
					</li>
				{{endforeach}}
			</ul>
		{{endif}}

		{{if $node->description}}
			<br>
			<div class='ipsType_richText ipsType_medium'>{$node->description|raw}</div>
		{{endif}}
		
		<hr class='ipsHr'>

		{{if !$node->redirect_on}}
			{{if method_exists( $node, 'lastPost' ) and $lastPost = $node->lastPost()}}
				<div class='ipsPhotoPanel ipsPhotoPanel_tiny'>
					{template="userPhoto" app="core" group="global" params="$lastPost['author'], 'tiny'"}
					<div>
						<ul class='ipsList_reset'>
							<li><a href="{$lastPost['topic_url']}" class='ipsType_break' title='{$lastPost['topic_title']}'>{truncate="$lastPost['topic_title']" length="30"}</a></li>
							<li>{lang="byline_nodate" htmlsprintf="$lastPost['author']->link()"}, <span class='ipsType_light'>{datetime="$lastPost['date']"}<span></li>
						</ul>
					</div>
				</div>
			{{else}}
				<p class='ipsType_light ipsType_reset'>{{if $node->password}}{lang="no_forum_posts_password"}{{else}}{lang="no_forum_posts"}{{endif}}</p>
			{{endif}}
		{{endif}}
		
	</div>
{{endif}}