<ips:template parameters="" />
<div class="collabLayout">
	{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack('__app_collab')"}

	{{foreach \IPS\collab\Category::roots() as $category}}
		{{if $category->can( 'view' )}}
		<section class="collabCategoryIndex">
			<a href='{$category->url()}'>
			{$category->coverPhoto( 'index' )|raw}
			</a>
		</section>
		{{endif}}
	{{endforeach}}
</div>