<ips:template parameters="$collab" />
<div data-controller='core.front.core.commentFeed' data-commentsType='reviews' data-baseURL='{$collab->url()}' {{if $collab->isLastPage('reviews')}}data-lastPage{{endif}}>
	{{if $collab->canReview()}}
		{{if $collab->locked()}}
			<strong class='ipsType_warning'><i class='fa fa-info-circle'></i> {lang="item_locked_can_review"}</strong>
		{{endif}}
		<div id='elFileReviewForm'>
			{$collab->reviewForm()|raw}
		</div>
	{{else}}
		{{if $collab->locked()}}
			{template="commentUnavailable" group="forms" location="front" app="core" params="'item_locked_cannot_comment'"}
		{{elseif \IPS\Member::loggedin()->restrict_post}}
			{template="commentUnavailable" group="forms" location="front" app="core" params="'restricted_cannot_comment', \IPS\Member::loggedIn()->warnings(5,NULL,'rpa'), \IPS\Member::loggedIn()->restrict_post"}
		{{elseif $collab->hasReviewed()}}
			<!-- Already reviewed -->
		{{elseif \IPS\Member::loggedIn()->restrict_post}}
			{template="reviewUnavailable" group="forms" location="front" app="core" params="'restricted_cannot_comment'"}
		{{elseif \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
			{template="reviewUnavailable" group="forms" location="front" app="core" params="'unacknowledged_warning_cannot_post', \IPS\Member::loggedIn()->warnings( 1, FALSE )"}
		{{else}}
			{template="reviewUnavailable" group="forms" location="front" app="core" params="'restricted_cannot_comment'"}
		{{endif}}
	{{endif}}
	{{if count( $collab->reviews() )}}
		<div class="ipsClearfix ipsSpacer_both">
			{{if $collab->reviewPageCount() > 1}}
				<div class="ipsPos_left ipsResponsive_noFloat">
					{$collab->reviewPagination( array( 'tab', 'sort' ) )|raw}
				</div>
			{{endif}}
			<div class="ipsClearfix ipsPos_right ipsResponsive_hidePhone">
				<ul class="ipsButtonRow ipsClearfix">
					<li data-action="tableFilter">
						<a href="{$collab->url()->setQueryString( array( 'tab' => 'reviews', 'page' => 1, 'sort' => 'helpful' ) )}" class="{{if !isset( request.sort ) or request.sort != 'newest'}}ipsButtonRow_active{{endif}}" data-action="filterClick">{lang="most_helpful"}</a>
					</li>
					<li data-action="tableFilter">
						<a href="{$collab->url()->setQueryString( array( 'tab' => 'reviews', 'page' => 1, 'sort' => 'newest' ) )}" class="{{if isset( request.sort ) and request.sort == 'newest'}}ipsButtonRow_active{{endif}}" data-action="filterClick">{lang="newest"}</a>
					</li>
				</ul>
			</div>
		</div>
		
		<div data-role='commentFeed' data-controller='core.front.core.moderation'>
			<form action="{$collab->url()->setQueryString( 'do', 'multimodReview' )}" method="post" data-ipsPageAction data-role='moderationTools'>
				{{$reviewCount=0; $timeLastRead = $collab->timeLastRead(); $lined = FALSE;}}
				{{foreach $collab->reviews() as $review}}
					{{if !$lined and $timeLastRead and $timeLastRead->getTimestamp() < $review->mapped('date')}}
						{{if $lined = TRUE and $reviewCount}}
							<hr class="ipsCommentUnreadSeperator">
						{{endif}}
					{{endif}}
					{{$reviewCount++;}}
					{$review->html()|raw}
				{{endforeach}}
				{template="commentMultimod" app="core" group="global" params="$collab, 'review'"}
			</form>
		</div>
		{{if $collab->reviewPageCount() > 1}}
			<div>
				{$collab->reviewPagination( array( 'tab', 'sort' ) )|raw}
			</div>
		{{endif}}
	{{endif}}
</div>