<ips:template parameters="$collabs, $orientation='vertical'" />
{{if !empty( $collabs ) }}
	<h3 class='ipsWidget_title ipsType_reset'>{lang="block_latestCollabs"}</h3>

	{{if $orientation == 'vertical'}}
		<div class='ipsPad_half ipsWidget_inner'>
			<ul class='ipsDataList ipsDataList_reducedSpacing'>
				{{foreach $collabs as $collab}}
					<li class='ipsDataItem{{if $collab->unread()}} ipsDataItem_unread{{endif}}{{if $collab->hidden()}} ipsModerated{{endif}}'>
						<div class='ipsDataItem_icon ipsPos_top'>
							{template="userPhoto" group="global" app="core" params="$collab->author(), 'tiny'"}
						</div>
						<div class='ipsDataItem_main'>
							<a href="{$collab->url()->setQueryString( 'do', 'getLastComment' )}" title='{lang="view_this_topic" sprintf="$collab->title"}' class='ipsDataItem_title ipsType_break'>{wordbreak="$collab->title"}</a>
							{{if $collab->mapped('featured') || $collab->hidden() === -1 || $collab->hidden() === 1}}
								<span>
									{{if $collab->hidden() === -1}}
										<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$collab->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
									{{elseif $collab->hidden() === 1}}
										<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
									{{endif}}
									{{if $collab->mapped('featured')}}
										<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
									{{endif}}
								</span>
							{{endif}}
							<br>
							<span class='ipsType_light ipsType_small'>{lang="byline_nodate" htmlsprintf="$collab->author()->link()"}</span>
						</div>
					</li>
				{{endforeach}}
			</ul>
		</div>
	{{else}}
		<div class='ipsWidget_inner'>
			<ul class='ipsDataList'>
				{{foreach $collabs as $collab}}
					{template="row" group="global" app="collab" params="NULL, NULL, $collab, FALSE"}
				{{endforeach}}
			</ul>
		</div>
	{{endif}}
{{endif}}