<ips:template parameters="$sponsor, $collab, $membership, $email" />

<p>
  <a href="{$sponsor->url()}">{$sponsor->name}</a> has invited you to join the {expression="mb_strtolower($collab->collab_singular)"} "<a href="{$collab->url()}>">{$collab->title}</a>".
</p>

{$membership->collab_notes|raw}

<br>
<a href="{url='app=collab&module=collab&controller=collabs&id={$collab->collab_id}&do=joinRequest'}" style="color: #ffffff; font-family: 'Helvetica Neue', helvetica, sans-serif; text-decoration: none; font-size: 14px; background: {setting="email_color"}; line-height: 32px; padding: 0 10px; display: inline-block; border-radius: 3px;">Send Reply</a>